// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_id_ from "./routes/[id].tsx";
import * as $_listId_ from "./routes/[listId].tsx";
import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_check_duplicates from "./routes/api/check-duplicates.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_login from "./routes/api/login.ts";
import * as $archive from "./routes/archive.tsx";
import * as $archive2 from "./routes/archive2.tsx";
import * as $data from "./routes/data.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $index from "./routes/index.tsx";
import * as $logindex from "./routes/logindex.tsx";
import * as $logout from "./routes/logout.ts";
import * as $qr from "./routes/qr.tsx";
import * as $s from "./routes/s.tsx";
import * as $ArchiveView from "./islands/ArchiveView.tsx";
import * as $ArchiveView2 from "./islands/ArchiveView2.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $QrCodeGenerator from "./islands/QrCodeGenerator.tsx";
import * as $TopBar from "./islands/TopBar.tsx";
import * as $UrlInput from "./islands/UrlInput.tsx";
import * as $UrlShortenerView from "./islands/UrlShortenerView.tsx";
import * as $qrcode from "./islands/qrcode.tsx";
import { type Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/[id].tsx": $_id_,
    "./routes/[listId].tsx": $_listId_,
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/check-duplicates.ts": $api_check_duplicates,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/login.ts": $api_login,
    "./routes/archive.tsx": $archive,
    "./routes/archive2.tsx": $archive2,
    "./routes/data.tsx": $data,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/index.tsx": $index,
    "./routes/logindex.tsx": $logindex,
    "./routes/logout.ts": $logout,
    "./routes/qr.tsx": $qr,
    "./routes/s.tsx": $s,
  },
  islands: {
    "./islands/ArchiveView.tsx": $ArchiveView,
    "./islands/ArchiveView2.tsx": $ArchiveView2,
    "./islands/Counter.tsx": $Counter,
    "./islands/QrCodeGenerator.tsx": $QrCodeGenerator,
    "./islands/TopBar.tsx": $TopBar,
    "./islands/UrlInput.tsx": $UrlInput,
    "./islands/UrlShortenerView.tsx": $UrlShortenerView,
    "./islands/qrcode.tsx": $qrcode,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
